workflows:
  - name: checks
    remove_jobs:
      - build-documentation-and-check-links
  - name: gh-pages
    remove_jobs:
      - deploy-documentation
    step_customizations:
      - action: REPLACE
        job: build-documentation
        step_id: build-documentation
        content:
          - name: Build Documentation
            id: build-documentation
            run: echo Do nothing
      - action: REPLACE
        job: build-documentation
        step_id: upload-artifact
        content:
          - name: Upload Artifact
            id: upload-artifact
            run: echo Do nothing
  - name: build-and-publish
    step_customizations:
      - action: REPLACE
        job: build-and-publish
        step_id: publish-release-to-github
        content:
          - name: Dummy Publish Release to GitHub
            id: publish-release-to-github
            run: echo Not needed because this is managed in the SLC-CD workflow
