Resources:
  CodeBuildCredentials:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      ServerType: GITHUB
      AuthType: PERSONAL_ACCESS_TOKEN
      Username: "{{ '{{' }}resolve:secretsmanager:{{secret_name}}:SecretString:{{secret_user_key}}}}"
      Token: "{{ '{{' }}resolve:secretsmanager:{{secret_name}}:SecretString:{{secret_token_key}}}}"
