name: Run Unit Tests

on: [push]

jobs:
  check_setup_py:
    environment: AWS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/prepare_poetry_env

    - name: Run pytest
      run: poetry run pytest
      env: # Set the secret as an env variable
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
