name: Checks

on:
  pull_request:

jobs:
  Version-Check:
    name: Version
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0

      - name: Check Version(s)
        run: |
          poetry run version-check exasol_script_languages_container_ci_setup/version.py

  lint-job:
    name: Linting and Type checks (Python-${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.15.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Unit Tests
        run: poetry run nox -s test:unit

      - name: Run Lint
        run: poetry run nox -s lint:code

      - name: Run type-check
        run: poetry run nox -s lint:typing

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ".lint-python-${{ matrix.python-version }}.txt"
          path: .lint.txt

  Completed:
    name: Completed
    needs: [ Version-Check, lint-job ]
    runs-on: ubuntu-latest
    steps:
      - name: Fiinished
        run: echo Finished
