name: Checks

on:
  workflow_call:

jobs:

  build-matrix:
    name: Generate Build Matrix
    uses: ./.github/workflows/matrix-python.yml

  Experiment:
    name: Get first python version from build matrix
    needs: [ build-matrix ]
    runs-on: ubuntu-24.04
    env:
      BUILD_MATRIX: ${{ needs.build-matrix.outputs.matrix }}
    steps:

      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Extract first Python version from build matrix
        run: |
          echo Build Matrix: "$BUILD_MATRIX"
          PYTHON_VERSION=$(echo "$BUILD_MATRIX" | jq '."python-version"[0]')
          echo "First python version in Build Matrix: $PYTHON_VERSION"
