name: Run Unit Tests

on: [push]

jobs:
  run_unit_tests:
    environment: AWS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python & Poetry Environment
      uses: exasol/python-toolbox/.github/actions/python-environment@1.0.1
      with:
        python-version: "3.10"
        poetry-version: '2.1.2'
    - name: Run pytest
      run: poetry run pytest
      env: # Set the secret as an env variable
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
