name: CI

on:
  pull_request:
      types: [opened, synchronize, reopened]
  # removed schedule as not needed in this project

jobs:
  merge-gate:
    name: Merge Gate
    uses: ./.github/workflows/merge-gate.yml
    secrets: inherit
    permissions:
      contents: read

  report:
    name: Report
    needs:
      - merge-gate
    uses: ./.github/workflows/report.yml
    secrets: inherit
    permissions:
      contents: read
