name: CI

on:
  push:
    branches-ignore:
      - "github-pages/*"
      - "gh-pages/*"
      - "main"
      - "master"
  # removed schedule as not needed in this project

jobs:

  CI:
    uses: ./.github/workflows/merge-gate.yml
    secrets: inherit

  # removed #Metrics as this does not work for this project
