name: Merge-Gate

on:
  workflow_call:
    # Manually added AWS Secrets here
    secrets:
      AWS_CLOUDFORMATION_VALIDATOR_ACCESS_KEY_ID:
        required: true
      AWS_CLOUDFORMATION_VALIDATOR_ACCESS_KEY_SECRET:
        required: true
      AWS_CLOUDFORMATION_VALIDATOR_DEFAULT_REGION:
        required: true
jobs:

  fast-checks:
    name: Fast
    uses: ./.github/workflows/checks.yml

  slow-checks:
    name: Slow
    uses: ./.github/workflows/slow-checks.yml
    secrets: inherit #added manually

  # This job ensures inputs have been executed successfully.
  approve-merge:
    name: Allow Merge
    runs-on: ubuntu-24.04
    # If you need additional jobs to be part of the merge gate, add them below
    needs: [ fast-checks, slow-checks ]

    # Each job requires a step, so we added this dummy step.
    steps:
      - name: Approve
        run: |
          echo "Merge Approved"
