name: Validate SLC Github workflows

on:
  pull_request:

jobs:

  Validate-SLC-Github-Workflows:
    name: Validate-Github-workflows
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Update Github workflow files
        run: poetry run -- nox -s update-integration-test-github-workflows -- --test-only

      - name: Check Git status
        run: |
          git status --porcelain=v1 -uno
          git diff --cached; git diff --cached --summary;
          [ -z "$(git status --porcelain=v1 -uno 2>/dev/null)" ]
